# Game Modes
SURVIVAL_MODE = 'survival'
TIME_ATTACK_MODE = 'time_attack'
HARDCORE_SURVIVAL_MODE = 'hardcore_survival'
HARDCORE_TIME_ATTACK_MODE = 'hardcore_time_attack'
PRACTICE_MODE = 'practice'

GAME_MODES = [
    SURVIVAL_MODE,
    TIME_ATTACK_MODE,
    HARDCORE_SURVIVAL_MODE,
    HARDCORE_TIME_ATTACK_MODE,
]

# Game Settings
DEFAULT_LIVES = 3
DEFAULT_TIME = 60
DEFAULT_SCORE = 0

