# Generated by Django 5.2 on 2025-05-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='score',
            new_name='ha_score',
        ),
        migrations.AddField(
            model_name='player',
            name='hta_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='survival_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='time_attack_score',
            field=models.IntegerField(default=0),
        ),
    ]
