# Generated by Django 5.2 on 2025-06-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='chapter_played',
            field=models.IntegerField(default=0),
        ),
    ]
