# Generated by Django 5.2 on 2025-05-10 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='year_level',
        ),
    ]
