# Generated by Django 5.2 on 2025-06-08 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_player_chapter_played'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='chapter_played',
        ),
    ]
