# Generated by Django 5.2 on 2025-05-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField()),
                ('correct_commands', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 10), ('medium', 20), ('hard', 30)], default='easy', max_length=10)),
                ('hint', models.TextField(blank=True, default='No hints for this task')),
            ],
        ),
    ]
