# Generated by Django 5.2 on 2025-06-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('file_operations', 'File Operations'), ('process_management', 'Process Management'), ('networking', 'Networking'), ('permissions', 'Permissions'), ('text_processing', 'Text Processing'), ('system_info', 'System Information'), ('other', 'Other')], default='other', help_text='Category of the task', max_length=20)),
                ('task', models.TextField()),
                ('correct_commands', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', '10'), ('medium', '20'), ('hard', '30')], default='easy', max_length=10)),
                ('hint', models.TextField(blank=True, default='No hints for this task')),
            ],
        ),
    ]
