# Generated by Django 5.2 on 2025-06-10 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('correct_commands', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', '10'), ('medium', '20'), ('hard', '30')], default='easy', max_length=10)),
                ('category', models.CharField(choices=[('file_operations', 'File Operations'), ('process_management', 'Process Management'), ('networking', 'Networking'), ('permissions', 'Permissions'), ('text_processing', 'Text Processing'), ('system_info', 'System Information'), ('other', 'Other')], default='other', max_length=20)),
                ('hint', models.TextField(blank=True, default='No hints for this task')),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_name', models.CharField(max_length=255)),
                ('instructor_sentence', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.chapter')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.task')),
            ],
        ),
    ]
