# Generated by Django 5.2 on 2025-06-06 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('number', models.IntegerField(unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_missions', to='game.chapter')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missions', to='game.task')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='missions',
            field=models.ManyToManyField(related_name='chapters', through='game.Mission', to='game.task'),
        ),
    ]
