# Generated by Django 5.2 on 2025-06-08 16:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='missions',
        ),
        migrations.AddField(
            model_name='task',
            name='instructor_sentence',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='mission_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mission',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.chapter'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('file_operations', 'File Operations'), ('process_management', 'Process Management'), ('networking', 'Networking'), ('permissions', 'Permissions'), ('text_processing', 'Text Processing'), ('system_info', 'System Information'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='task',
            field=models.CharField(max_length=255),
        ),
    ]
