# Generated by Django 5.2 on 2025-05-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('file_operations', 'File Operations'), ('process_management', 'Process Management'), ('networking', 'Networking'), ('permissions', 'Permissions'), ('text_processing', 'Text Processing'), ('system_info', 'System Information'), ('other', 'Other')], default='other', help_text='Category of the question', max_length=20),
        ),
    ]
