# Generated by Django 5.2 on 2025-05-18 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', '10'), ('medium', '20'), ('hard', '30')], default='easy', max_length=10),
        ),
    ]
