# Generated by Django 5.2 on 2025-06-08 16:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_remove_chapter_missions_task_instructor_sentence_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='instructor_sentence',
        ),
        migrations.RemoveField(
            model_name='task',
            name='mission_name',
        ),
        migrations.AddField(
            model_name='mission',
            name='instructor_sentence',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mission',
            name='mission_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
